package mover::Model::Auth;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

#__PACKAGE__->config(
#    schema_class => 'mover::Auth::Schema',
#    
#    
#);


#-------------------------------------------------------------------------------
#  Connect to Authorization Schema
#  For Testing Only as of Sep 17 2012
#-------------------------------------------------------------------------------
__PACKAGE__->config(
    schema_class => 'mover::Auth::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:auth.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

mover::Model::Auth - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<mover>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<mover::Auth::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

austin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
